---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: ququiz-db-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.27" # cpu vps gak suport avx , jadi gak bisa versi 5 keatas (https://github.com/mongodb/mongodb-kubernetes-operator/issues/959)
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWrite
          db: lintang_quiz
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name. (https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml)
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "1.5"
                  memory: 1000M
                requests:
                  cpu: "0.2"
                  memory: 200M
             
            # - name: mongodb-agent ## udah pernah pake volume gak bisa error , yang belum dicoba container ini dicomment
            #   resources: 
            #     limits:
            #       cpu: "1"
            #       memory: 1000M
            #     requests:
            #       cpu: "0.2"
            #       memory: 200M
              
          initContainers:
            - name: mongodb-agent-readinessprobe
              resources:
                limits:
                  cpu: "2"
                  memory: 200M
                requests:
                  cpu: "1"
                  memory: 100M
     
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
type: Opaque
stringData:
  password: lintang