---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/mongodb
    targetRevision: 15.6.1
    chart: mongodb
    helm:
      version: v3
      releaseName: mongodb
      passCredentials: false
      values: |
        architecture: replicaset
        persistence:
          enabled: true
          storageClass: local-storage
          accessModes:
            - ReadWriteOnce
          size: 10Gi
        resources:
        limits:
          memory: 1Gi
          cpu: 1.5
       
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true