---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-command
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ququiz/argocd-k8s-ququiz
    targetRevision: HEAD
    path: k8s-deployment/app/quiz-command
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true