---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app:  auth
    spec:
      replicas: 1
      containers:
      - name:  auth
        image: docker.io/lintangbirdas/ququiz-auth-adam:v1.0
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            value: lintang
          - name: POSTGRES_PASSWORD
            value: lintang
          - name: POSTGRES_HOST
            value: my-pgsql-cluster-rw.postgres
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_DATABASE
            value: ququiz
        resources:
          limits:
            memory: "700Mi"
            cpu: "700m"
        ports:
        - containerPort: 3000
          name: rest-api
        - containerPort: 4000
          name: grpc
    
  

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector: 
    app: auth
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: grpc
      port: 4000
      protocol: TCP
      targetPort: 4000
 
