

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app:  auth
    spec:
      containers:
      - name:  auth
        image: docker.io/lintangbirdas/ququiz-auth-adam:3
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            value: lintang
          - name: POSTGRES_PASSWORD
            value: lintang
          - name: POSTGRES_HOST
            value: my-pgsql-cluster-rw.postgres
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_DATABASE
            value: ququiz
          - name: ACCESS_TOKEN_ALGORITHM
            value: ES512
          - name: JWT_PRIVATE_KEY
            value: "-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIB7Dwpk55oVgPcVjTU5P4M5FsmBj6GGn1aMaQbjZQL4jBDKY2I34+G\nAhRoTVHowSaSpv9oKbmBqlNzcCsqInV6lpCgBwYFK4EEACOhgYkDgYYABACh3HAV\n2IUpZMb9lTu9c92TyjH6c1TUmbGyYjyLy1ith/pDGbAHPXeNL89mxvx0lswVjdhM\nwyKHpIrPt75xDrwhuADsGdjl9gVARPhI0dVf/NofonvQREkuxGtquZZJew1sxuep\neUiSiithd4Cf2+wtuv9E/D0NhqirgmtD44axzgsczA==\n-----END EC PRIVATE KEY-----\n"
          - name: JWT_PUBLIC_KEY
            value: "-----BEGIN PUBLIC KEY-----\nMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAodxwFdiFKWTG/ZU7vXPdk8ox+nNU\n1JmxsmI8i8tYrYf6QxmwBz13jS/PZsb8dJbMFY3YTMMih6SKz7e+cQ68IbgA7BnY\n5fYFQET4SNHVX/zaH6J70ERJLsRrarmWSXsNbMbnqXlIkoorYXeAn9vsLbr/RPw9\nDYaoq4JrQ+OGsc4LHMw=\n-----END PUBLIC KEY-----\n"
          - name: REFRESH_TOKEN_ALGORITHM
            value: HS256
          - name: REFRESH_TOKEN_SECRET
            value: "coX0s+/NKBQEnZMFcjtWrwYcwydOCcWHYV8Vtq2SsLjWVaGrtJBhmnJ70yD/9n74crZrEBgZEYs8XCIIERcVMSWSJGhJHQ8HimcJ9tmt8S2ZO8UVB5Mq2UzLCsCtDq8m4J9JXWk5qS5QTlIzW5t3d4m7DIqFMEikOUSp8MMgk+oXkH1stoYbXKSk8i7RJOHpPKLQRMFNOXLhv7xi+f9TEuRxFAvsjUGb4JsrxaICBf6LCXznKic4WJ0tZPLq98wW3zgxOVPjJPgDxiEAyYIZa1b/nZ0iZSJtnrCKvhamdqZkiYxW0ikZWa7TnTkGi3pZFJMqbW72VPBRl+059ZvOzA=="

        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          name: rest-api
        - containerPort: 4000
          name: grpc
    
  

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector: 
    app: auth
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: grpc
      port: 4000
      protocol: TCP
      targetPort: 4000
 
