node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email lintangbirdasaputra23@gmail.com"
                        sh "git config user.name lintang-b-s"
                        //sh "git switch master"
                        sh "cat notification.yaml"
                        sh "sed -i 's+docker.io/lintangbirdas/ququiz-notification-service-bagas.*+docker.io/lintangbirdas/ququiz-notification-service-bagas:${DOCKERTAG}+g' notification.yaml"
                        sh "cat notification.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/ququiz/argocd-k8s-ququiz.git HEAD:main"
      }
    }
  }
}
}