---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app:  notification
    spec:
      containers:
      - name:  notification
        image: docker.io/lintangbirdas/ququiz-notification-service-bagas:1
        imagePullPolicy: Always
        env:
          - name: RABBITMQ_HOST
            value: amqp://default_user_m5S03wBum5eTjtM0auU:v4lzdb3Ebl1rs2V9_DzXOj40jgqG9mFQ@10.233.1.153:5672/ # sesuain sama ip service headless rabbitmq
          
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
        - containerPort: 3000
          name: rest-api
        
    
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector: 
    app: notification
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000

 
