

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app:  notification
        
    spec:
      containers:
      - name:  notification
        image: docker.io/lintangbirdas/ququiz-notification-service-bagas:12
        imagePullPolicy: Always
        env:
          - name: RABBITMQ_HOST
            value: guest:guest@10.233.59.55:5672/ # sesuain sama ip service headless rabbitmq
          - name: QUEUE_UPCOMING_QUIZ
            value: upcoming_quiz
          - name: QUEUE_QUIZ_RESULT
            value: quiz_result
          - name: MAIL_HOST
            value: sandbox.smtp.mailtrap.io
          - name: MAIL_PORT
            value: '2525'
          - name: MAIL_USERNAME
            value: 1427f83ffe1fef
          - name: MAIL_PASSWORD
            value: b9d4f47573de85
          - name: MAIL_FROM_ADDRESS
            value: ququiz.dev@gmail.com
          - name: MAIL_FROM_NAME
            value: QuQuiz
        resources:
          limits:
            memory: "800Mi"
            cpu: 800m"
        ports:
        - containerPort: 3000
          name: rest-api
        
    
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector: 
    app: notification
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000

 
