---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app:  notification
    spec:
      replicas: 1
      containers:
      - name:  notification
        image: docker.io/lintangbirdas/ququiz-notification-service-bagas:1
        imagePullPolicy: Always
        env:
          - name: RABBITMQ_HOST
            value: amqp://default_user_BOelQt8vxauYDMZRMqq:IyqQrk-a0BNgWv6EeLAnYGgR6U8rSdh6@10.233.61.171:5672/ # sesuain sama ip service headless rabbitmq
          
        resources:
          limits:
            memory: "500Mi"
            cpu: "700m"
        ports:
        - containerPort: 3000
          name: rest-api
        
    
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector: 
    app: notification
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000

 
