---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-command
  template:
    metadata:
      labels:
        app:  quiz-command
    spec:
      containers:
      - name:  quiz-command
        image: docker.io/lintangbirdas/quiz-command-service-adam:24
        imagePullPolicy: Always
        env:
        
          - name: MONGO_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0&readPreference=secondaryPreferred
          - name: DKRON_API_URL
            value: http://dkron-svc:8080/v1
          - name: RABBITMQ_URL
            value: amqp://default_user_mcO73Wjq65H_2OCTtRU:yCUxtKFfFVZRh9a3dKxo8zNbDIaQiyM5@10.233.10.140:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: QUIZ_SERVICE_URL
            value: http://quiz-query-service:3000
          - name: USERS_SERVICE_GRPC_URL
            value: http://auth-service:4000
          - name: SCORING_SERVICE_URL
            value: http://scoring-service:3503
          - name: JWT_PUBLIC_KEY
            value: "-----BEGIN PUBLIC KEY-----\nMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAodxwFdiFKWTG/ZU7vXPdk8ox+nNU\n1JmxsmI8i8tYrYf6QxmwBz13jS/PZsb8dJbMFY3YTMMih6SKz7e+cQ68IbgA7BnY\n5fYFQET4SNHVX/zaH6J70ERJLsRrarmWSXsNbMbnqXlIkoorYXeAn9vsLbr/RPw9\nDYaoq4JrQ+OGsc4LHMw=\n-----END PUBLIC KEY-----\n"
     
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          name: rest-api
        
    

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-command-service
spec:
  selector: 
    app: quiz-command
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000

 
