---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-command
  template:
    metadata:
      labels:
        app:  quiz-command
    spec:
      containers:
      - name:  quiz-command
        image: docker.io/lintangbirdas/quiz-command-service-adam:16
        imagePullPolicy: Always
        env:
        
          - name: MONGO_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0&readPreference=secondaryPreferred
          - name: DKRON_URL
            value: http://dkron-svc:8080/v1/jobs
          - name: RABBITMQ_URL
            value: amqp://default_user_BOelQt8vxauYDMZRMqq:IyqQrk-a0BNgWv6EeLAnYGgR6U8rSdh6@10.233.61.171:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: QUIZ_SERVICE_URL
            value: http://quiz-query-service:3000
          - name: USERS_SERVICE_GRPC_URL
            value: http://auth-service:4000
          - name: SCORING_SERVICE_URL
            value: http://scoring-service:3503
         
        resources:
          limits:
            memory: "500Mi"
            cpu: "700m"
        ports:
        - containerPort: 3000
          name: rest-api
        
    

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-command-service
spec:
  selector: 
    app: quiz-command
  ports:
    - name: rest-api
      port: 3000
      protocol: TCP
      targetPort: 3000

 
