apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example-mongodb-ququiz-12
  labels:
    app: example-mongodb-svc
spec:
  capacity:
    storage: 10Gi # update this according to your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # most common mode, but check your application requirement
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage" # no storage class , harus tanpa storageclass biar bisa jalan mongodbnya
  local:
    path: /data/volumes/pv-mongodb-st2  # update this path according to your needs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nodebiznet # replace this with your actual node nam