apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
    limits:
      cpu: 800m
      memory: 800Mi
  persistence:
    storageClassName: local-storage
    storage: 5Gi
#  rabbitmq:
  #  additionalPlugins:
    #  - rabbitmq_management
