apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
    limits:
      cpu: 2500m
      memory: 2500Mi
  persistence:
    storageClassName: local-storage
    storage: 10Gi
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
      loopback_users = none

