---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkron
spec:
  selector:
    matchLabels:
      app: dkron
  template:
    metadata:
      labels:
        app:  dkron
    spec:
      hostNetwork: true # harus ada biar bisa install curl
      dnsPolicy: "ClusterFirstWithHostNet" #"Default" Default gak bisa request ke transcoder-worker-servicce..## biar bisa install curl
      containers:
      - name:  dkron
        image: dkron/dkron:4.0.0-beta5 #docker.io/dkron/dkron:3.2.7 yg versi in job yang dibuat quiz command service kosong
        resources:
        limits:
          memory: "1500Mi"
          cpu: "1500m"
        
        volumeMounts:
        - mountPath: /curl
          name: dkroncurl
        - name: dirbuatcurl
          mountPath: /bisa
        - name: tz-config
          mountPath: /etc/localtime
          readOnly: true
        command: ["/usr/local/bin/dkron", "agent", "--server", "--bootstrap-expect=1"] #, "--data-dir=/dkron.data
        ports:
          - containerPort: 8080
      volumes:
        - name: dirbuatcurl
          emptyDir: {}
        - name: dkroncurl
          configMap:
            name: dkroncurl
        - name: tz-config
          hostPath:
            path: /etc/localtime
            type: File
   

---
apiVersion: v1
kind: Service
metadata: 
  name: dkron-svc
spec: 
  selector:
    app: dkron
  ports: 
  - port: 8080
    targetPort: 8080
  #   nodePort: 31022
  # type: NodePort
