# pv/pv-data.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example-mongodb-ququiz-logs-3
  labels:
    app: example-mongodb-svc
spec:
  capacity:
    storage: 5Gi # update this according to your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # most common mode, but check your application requirement
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # no storage class , harus tanpa storageclass biar bisa jalan mongodbnya
  local:
    path: /data/volumes/pv-mongodb-logs-3  # update this path according to your needs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1 # replace this with your actual node name