---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-query
  template:
    metadata:
      labels:
        app:  quiz-query
    spec:
      containers:
      - name:  quiz-query
        image: docker.io/lintangbirdas/quiz-query-service:14
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0&readPreference=secondaryPreferred #?replicaSet=ququiz-db-mongodb  #&readPreference=secondaryPreferred
          - name: MONGO_WRITE_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0 #?replicaSet=ququiz-db-mongodb  #&readPreference=secondaryPreferred
          - name: RABBITMQ_ADDRESS
            value: amqp://default_user_EZtmRyAdl7Al_Myzbka:DvFE319-ov9ESIKN49flM6NO0b1lkYqN@10.233.47.129:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: REDIS_ADDR
            value: redis-headless.redis:6379
          - name: REDIS_PASSWORD
            value: lintang
          - name: APP_ENV
            value: k8s
          - name: MONGO_DB
            value: test
      
          # - name: DKRON_URL
          #   value: http://dkron-svc:8080/v1/jobs
          # - name: TRANSCODER_WORKER_URL
          #   value: lintang-transcoder-worker-service.default.svc.cluster.local:9995
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
        ports:
        - containerPort: 3503
          name: rest-api
        - containerPort: 6005
          name: grpc
  
  

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-query-service
spec:
  selector: 
    app: quiz-query
  ports:
    - name: rest-api
      port: 3503
      protocol: TCP
      targetPort: 3503
    - name: grpc
      port: 6005
      protocol: TCP
      targetPort: 6005
      # nodePort: 31203

  # type: NodePort
