---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-query
spec:
  selector:
    matchLabels:
      app: quiz-query
  template:
    metadata:
      labels:
        app:  quiz-query
    spec:
      replicas: 1
      containers:
      - name:  quiz-query
        image: docker.io/lintangbirdas/quiz-query-service:1
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0 #?replicaSet=ququiz-db-mongodb  #&readPreference=secondaryPreferred
          - name: MONGO_WRITE_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0 #?replicaSet=ququiz-db-mongodb  #&readPreference=secondaryPreferred
          - name: RABBITMQ_ADDRESS
            value: amqp://default_user_BOelQt8vxauYDMZRMqq:IyqQrk-a0BNgWv6EeLAnYGgR6U8rSdh6@10.233.61.171:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: REDIS_ADDR
            value: redis-headless.redis:6379
          - name: REDIS_PASSWORD
            value: lintang
          - name: APP_ENV
            value: k8s
          - name: MONGO_DB
            value: test
        
          # - name: DKRON_URL
          #   value: http://dkron-svc:8080/v1/jobs
          # - name: TRANSCODER_WORKER_URL
          #   value: lintang-transcoder-worker-service.default.svc.cluster.local:9995
        resources:
          limits:
            memory: "700Mi"
            cpu: "700m"
        ports:
        - containerPort: 3504
          name: rest-api
    
  

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-query-service
spec:
  selector: 
    app: quiz-query
  ports:
    - name: rest-api
      port: 3504
      protocol: TCP
      targetPort: 3504
 
      # nodePort: 31203

  # type: NodePort
