---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-query
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quiz-query
  template:
    metadata:
      labels:
        app:  quiz-query
        
    spec:
      containers:
      - name:  quiz-query
        image: docker.io/lintangbirdas/quiz-query-service:24
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3503
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path:  /healthz
            port: 3503
          initialDelaySeconds: 3
          periodSeconds: 4
          failureThreshold: 8
        startupProbe:
          httpGet:
            path: /healthz
            port: 3503
          failureThreshold: 10
          periodSeconds: 10
        env:
          - name: MONGO_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0&readPreference=secondaryPreferred #?replicaSet=ququiz-db-mongodb  #&readPreference=secondaryPreferred
          - name: MONGO_WRITE_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0 #?replicaSet=ququiz-db-mongodb  #&readPreference=secondaryPreferred
          - name: RABBITMQ_ADDRESS
            value: amqp://guest:guest@10.233.59.55:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: REDIS_ADDR
            value: redis-headless.redis:6379
          - name: REDIS_PASSWORD
            value: lintang
          - name: APP_ENV
            value: k8s
          - name: MONGO_DB
            value: test
          - name: AUTH_GRPC_URL
            value: auth-service:4000
      
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1500m"
        ports:
        - containerPort: 3503
          name: rest-api
        - containerPort: 6005
          name: grpc
  
  

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-query-service
spec:
  selector: 
    app: quiz-query
  ports:
    - name: rest-api
      port: 3503
      protocol: TCP
      targetPort: 3503
    - name: grpc
      port: 6005
      protocol: TCP
      targetPort: 6005
      # nodePort: 31203

  # type: NodePort
