---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-query
spec:
  selector:
    matchLabels:
      app: quiz-query
  template:
    metadata:
      labels:
        app:  quiz-query
    spec:
      replicas: 3
      containers:
      - name:  quiz-query
        image: docker.io/lintangbirdas/scoring-service:3
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            value: mongodb://admin:lintang@ququiz-db-mongodb-0.ququiz-db-mongodb-svc.mongodb.svc.cluster.local:27017,ququiz-db-mongodb-1.ququiz-db-mongodb-svc.mongodb.svc.cluster.local:27017,ququiz-db-mongodb-2.ququiz-db-mongodb-svc.mongodb.svc.cluster.local:27017/admin?replicaSet=ququiz-db-mongodb&ssl=false&readPreference=secondaryPreferred
          - name: RABBITMQ_ADDRESS
            value: amqp://default_user_qBofhrkSzzUoEDWve1t:ZciKwWU3f4ev5dFjmBnIMNDnvr4MjKfr@10.108.25.30:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: REDIS_ADDR
            value: redis-headless.redis:6379
          - name: REDIS_PASSWORD
            value: lintang
          - name: APP_ENV
            value: k8s
          # - name: DKRON_URL
          #   value: http://dkron-svc:8080/v1/jobs
          # - name: TRANSCODER_WORKER_URL
          #   value: lintang-transcoder-worker-service.default.svc.cluster.local:9995
        resources:
          limits:
            memory: "700Mi"
            cpu: "700m"
        ports:
        - containerPort: 3504
          name: rest-api
    
  

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-query-service
spec:
  selector: 
    app: quiz-query
  ports:
    - name: rest-api
      port: 3504
      protocol: TCP
      targetPort: 3504
 
      # nodePort: 31203

  # type: NodePort
