---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoring
spec:
  replicas: 4
  selector:
    matchLabels:
      app: scoring
  template:
    metadata:
      labels:
        app:  scoring
        
    spec:
      containers:
      - name:  scoring
        image: docker.io/lintangbirdas/scoring-service:10
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3504
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path:  /healthz
            port: 3504
          initialDelaySeconds: 3
          periodSeconds: 4
          failureThreshold: 8
        startupProbe:
          httpGet:
            path: /healthz
            port: 3504
          failureThreshold: 10
          periodSeconds: 10
        env:
          - name: MONGO_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0&readPreference=secondaryPreferred
          - name: RABBITMQ_ADDRESS
            value: amqp://guest:guest@10.233.59.55:5672/ # sesuain sama ip service headless rabbitmq  # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: MONGO_WRITE_URL
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?replicaSet=rs0
          
          - name: REDIS_ADDR
            value: redis-headless.redis:6379
          - name: REDIS_PASSWORD
            value: lintang
          - name: APP_ENV
            value: k8s
          - name: QUIZ_QUERY_GRPC_URL
            value: quiz-query-service:6005
          - name: AUTH_GRPC_CLIENT
            value: auth-service:4000

        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
        - containerPort: 3504
          name: rest-api
       

---
apiVersion: v1
kind: Service
metadata:
  name: scoring-service
spec:
  selector: 
    app: scoring
  ports:
    - name: rest-api
      port: 3504
      protocol: TCP
      targetPort: 3504
   
      # nodePort: 31203

  # type: NodePort
